version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: url_shortener_postgres
    environment:
      POSTGRES_USER: aryan
      POSTGRES_PASSWORD: aryan
      POSTGRES_DB: aryan
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
